R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
	"truck_01_base_f",
	"truck_02_base_f",
	"truck_03_base_f",
	"Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Repair_Red",
	"Exile_Car_Offroad_Repair_Beige",
	"Exile_Car_Offroad_Repair_White",
	"Exile_Car_Offroad_Repair_Blue",
	"Exile_Car_Offroad_Repair_DarkRed",
	"Exile_Car_Offroad_Repair_BlueCustom",
	"Exile_Car_Offroad_Repair_Guerilla01",
	"Exile_Car_Offroad_Repair_Guerilla02",	
	"Exile_Car_Offroad_Repair_Guerilla03",
	"Exile_Car_Offroad_Repair_Guerilla04",
	"Exile_Car_Offroad_Repair_Guerilla05",
	"Exile_Car_Offroad_Repair_Guerilla06",
	"Exile_Car_Offroad_Repair_Guerilla07",
	"Exile_Car_Offroad_Repair_Guerilla08",
	"Exile_Car_Offroad_Repair_Guerilla09",
	"Exile_Car_Offroad_Repair_Guerilla10",
	"Exile_Car_Offroad_Repair_Guerilla11",
	"Exile_Car_Offroad_Repair_Guerilla12",
	"Exile_Car_Van_Black", 
    "Exile_Car_Van_White", 
    "Exile_Car_Van_Red", 
  "Exile_Car_Van_Guerilla01", 
  "Exile_Car_Van_Guerilla02", 
  "Exile_Car_Van_Guerilla03", 
  "Exile_Car_Van_Guerilla04", 
  "Exile_Car_Van_Guerilla05", 
  "Exile_Car_Van_Guerilla06", 
  "Exile_Car_Van_Guerilla07", 
  "Exile_Car_Van_Guerilla08",
  "Exile_Car_Offroad_Rusty1", 
  "Exile_Car_Offroad_Rusty2", 
  "Exile_Car_Offroad_Rusty3", 
  "Exile_Car_Offroad_Red", 
  "Exile_Car_Offroad_Beige", 
  "Exile_Car_Offroad_White", 
  "Exile_Car_Offroad_Blue", 
  "Exile_Car_Offroad_DarkRed", 
  "Exile_Car_Offroad_BlueCustom", 
  "Exile_Car_Offroad_Guerilla01", 
  "Exile_Car_Offroad_Guerilla02", 
  "Exile_Car_Offroad_Guerilla03", 
  "Exile_Car_Offroad_Guerilla04", 
  "Exile_Car_Offroad_Guerilla05", 
  "Exile_Car_Offroad_Guerilla06", 
  "Exile_Car_Offroad_Guerilla07", 
  "Exile_Car_Offroad_Guerilla08", 
  "Exile_Car_Offroad_Guerilla09", 
  "Exile_Car_Offroad_Guerilla10", 
  "Exile_Car_Offroad_Guerilla11", 
  "Exile_Car_Offroad_Guerilla12",
  "Exile_Car_Offroad_Armed_Guerilla01", 
  "Exile_Car_Offroad_Armed_Guerilla02", 
  "Exile_Car_Offroad_Armed_Guerilla03", 
  "Exile_Car_Offroad_Armed_Guerilla04", 
  "Exile_Car_Offroad_Armed_Guerilla05", 
  "Exile_Car_Offroad_Armed_Guerilla06", 
  "Exile_Car_Offroad_Armed_Guerilla07", 
  "Exile_Car_Offroad_Armed_Guerilla08", 
  "Exile_Car_Offroad_Armed_Guerilla09", 
  "Exile_Car_Offroad_Armed_Guerilla10", 
  "Exile_Car_Offroad_Armed_Guerilla11", 
  "Exile_Car_Offroad_Armed_Guerilla12",
   "Exile_Car_SUV_Red", 
  "Exile_Car_SUV_Black", 
  "Exile_Car_SUV_Grey", 
  "Exile_Car_SUV_Orange",
	"Exile_Car_Van_Black",
	"Exile_Car_Van_Box_Black",
	"Exile_Car_Van_Fuel_Black",
	"Exile_Car_Zamak",
	"Exile_Car_Strider",
	"Exile_Car_Hunter",
	"Exile_Car_Tempest",
	"Exile_Car_HEMMT",
	"rhsusf_M1078A1P2_B_M2_wd_fmtv_usarmy",
	"rhsusf_M1078A1P2_B_M2_wd_open_fmtv_usarmy",
	"rhsusf_M1078A1P2_B_M2_wd_flatbed_fmtv_usarmy",
	"rhsusf_M1078A1P2_B_M2_d_fmtv_usarmy",
	"rhsusf_M1078A1P2_B_M2_d_open_fmtv_usarmy",
	"rhsusf_M1078A1P2_B_M2_d_flatbed_fmtv_usarmy",
	"RHS_Ural_Flat_MSV_01",
	"I_Truck_02_covered_F",
	"I_Truck_02_transport_F",
	"I_G_Van_01_transport_F",
	"I_G_Van_01_fuel_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_mover_F",
	"B_G_Van_01_transport_F",
	"B_G_Van_01_fuel_F",
	"O_Truck_03_transport_F",
	"O_Truck_03_covered_F",
	"rhsusf_m113d_usarmy_unarmed",
	"rhsusf_m113_usarmy_unarmed",
	"I_MRAP_03_F",
  "I_G_Offroad_01_F",
  "I_G_Offroad_01_armed_F",
  "B_MRAP_01_F",
  "B_MRAP_01_hmg_F",
  "B_G_Offroad_01_F",
  "B_G_Offroad_01_armed_F",
  "O_MRAP_02_F",
  "O_MRAP_02_hmg_F",
  "O_G_Offroad_01_F",
  "O_G_Offroad_01_armed_F",	
  "rhsusf_m1025_w_s_m2",
  "rhsusf_m1025_d",
  "rhsusf_m1025_w",
  "rhs_tigr_vdv",
  "rhs_tigr_vmf",
  "rhs_tigr_msv",
  "rhs_tigr_vv",
  "rhs_tigr_3camo_vdv",
  "rhs_tigr_3camo_vmf",
  "rhs_tigr_3camo_msv",
  "rhs_tigr_3camo_vv",
  "rhs_tigr_ffv_vdv",
  "rhs_tigr_ffv_vmf",
  "rhs_tigr_ffv_msv",
  "rhs_tigr_ffv_vv",
  "rhs_tigr_ffv_3camo_vdv",
  "rhs_tigr_ffv_3camo_vv",
  "rhs_uaz_open_MSV_01",
  "rhsusf_m998_w_s_2dr",
  "rhsusf_m988_d_s_2dr",
  "rhsusf_m988_w_s_2dr_halftop",
  "rhsusf_m998_d_s_2dr_fulltop",
  "rhsusf_m998_w_s_2dr_fulltop"
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
  "car_f",
   "Exile_Car_Offroad_Repair_Civillian",
	"Exile_Car_Offroad_Repair_Red",
	"Exile_Car_Offroad_Repair_Beige",
	"Exile_Car_Offroad_Repair_White",
	"Exile_Car_Offroad_Repair_Blue",
	"Exile_Car_Offroad_Repair_DarkRed",
	"Exile_Car_Offroad_Repair_BlueCustom",
	"Exile_Car_Offroad_Repair_Guerilla01",
	"Exile_Car_Offroad_Repair_Guerilla02",	
	"Exile_Car_Offroad_Repair_Guerilla03",
	"Exile_Car_Offroad_Repair_Guerilla04",
	"Exile_Car_Offroad_Repair_Guerilla05",
	"Exile_Car_Offroad_Repair_Guerilla06",
	"Exile_Car_Offroad_Repair_Guerilla07",
	"Exile_Car_Offroad_Repair_Guerilla08",
	"Exile_Car_Offroad_Repair_Guerilla09",
	"Exile_Car_Offroad_Repair_Guerilla10",
	"Exile_Car_Offroad_Repair_Guerilla11",
	"Exile_Car_Offroad_Repair_Guerilla12",
	"Exile_Car_Van_Black",
	"Exile_Car_Van_Box_Black",
	"Exile_Car_Van_Fuel_Black",
  "Exile_Car_Van_Black", 
  "Exile_Car_Van_White", 
  "Exile_Car_Van_Red", 
  "Exile_Car_Van_Guerilla01", 
  "Exile_Car_Van_Guerilla02", 
  "Exile_Car_Van_Guerilla03", 
  "Exile_Car_Van_Guerilla04", 
  "Exile_Car_Van_Guerilla05", 
  "Exile_Car_Van_Guerilla06", 
  "Exile_Car_Van_Guerilla07", 
  "Exile_Car_Van_Guerilla08",
  "Exile_Car_Offroad_Rusty1", 
  "Exile_Car_Offroad_Rusty2", 
  "Exile_Car_Offroad_Rusty3", 
  "Exile_Car_Offroad_Red", 
  "Exile_Car_Offroad_Beige", 
  "Exile_Car_Offroad_White", 
  "Exile_Car_Offroad_Blue", 
  "Exile_Car_Offroad_DarkRed", 
  "Exile_Car_Offroad_BlueCustom", 
  "Exile_Car_Offroad_Guerilla01", 
  "Exile_Car_Offroad_Guerilla02", 
  "Exile_Car_Offroad_Guerilla03", 
  "Exile_Car_Offroad_Guerilla04", 
  "Exile_Car_Offroad_Guerilla05", 
  "Exile_Car_Offroad_Guerilla06", 
  "Exile_Car_Offroad_Guerilla07", 
  "Exile_Car_Offroad_Guerilla08", 
  "Exile_Car_Offroad_Guerilla09", 
  "Exile_Car_Offroad_Guerilla10", 
  "Exile_Car_Offroad_Guerilla11", 
  "Exile_Car_Offroad_Guerilla12",
  "Exile_Car_Offroad_Armed_Guerilla01", 
  "Exile_Car_Offroad_Armed_Guerilla02", 
  "Exile_Car_Offroad_Armed_Guerilla03", 
  "Exile_Car_Offroad_Armed_Guerilla04", 
  "Exile_Car_Offroad_Armed_Guerilla05", 
  "Exile_Car_Offroad_Armed_Guerilla06", 
  "Exile_Car_Offroad_Armed_Guerilla07", 
  "Exile_Car_Offroad_Armed_Guerilla08", 
  "Exile_Car_Offroad_Armed_Guerilla09", 
  "Exile_Car_Offroad_Armed_Guerilla10", 
  "Exile_Car_Offroad_Armed_Guerilla11", 
  "Exile_Car_Offroad_Armed_Guerilla12",
  "Exile_Car_SUV_Red", 
  "Exile_Car_SUV_Black", 
  "Exile_Car_SUV_Grey", 
  "Exile_Car_SUV_Orange",
  "Exile_Car_Hatchback_Beige", 
  "Exile_Car_Hatchback_Green", 
  "Exile_Car_Hatchback_Blue", 
  "Exile_Car_Hatchback_BlueCustom", 
  "Exile_Car_Hatchback_BeigeCustom", 
  "Exile_Car_Hatchback_Yellow", 
  "Exile_Car_Hatchback_Grey", 
  "Exile_Car_Hatchback_Black", 
  "Exile_Car_Hatchback_Dark", 
  "Exile_Car_Hatchback_Rusty1", 
  "Exile_Car_Hatchback_Rusty2", 
  "Exile_Car_Hatchback_Rusty3", 
  "Exile_Car_Hatchback_Sport_Red", 
  "Exile_Car_Hatchback_Sport_Blue", 
  "Exile_Car_Hatchback_Sport_Orange", 
  "Exile_Car_Hatchback_Sport_White", 
  "Exile_Car_Hatchback_Sport_Beige", 
  "Exile_Car_Hatchback_Sport_Green",
  "Exile_Bike_QuadBike_Black", 
  "Exile_Bike_QuadBike_Blue", 
  "Exile_Bike_QuadBike_Red", 
  "Exile_Bike_QuadBike_White", 
  "Exile_Bike_QuadBike_Nato", 
  "Exile_Bike_QuadBike_Csat",
  "Exile_Bike_QuadBike_Fia", 
  "Exile_Bike_QuadBike_Guerilla01", 
  "Exile_Bike_QuadBike_Guerilla02",
  "Exile_Car_Strider",
  "Exile_Car_Hunter",
  "Exile_Car_Ifrit",
  "O_Quadbike_01_F",
  "O_G_Quadbike_01_F",
  "I_Quadbike_01_F",
  "I_G_Quadbike_01_F",
  "C_Quadbike_01_F",
  "I_MRAP_03_F",
  "I_G_Offroad_01_F",
  "I_G_Offroad_01_armed_F",
  "B_MRAP_01_F",
  "B_MRAP_01_hmg_F",
  "B_G_Offroad_01_F",
  "B_G_Offroad_01_armed_F",
  "O_MRAP_02_F",
  "O_MRAP_02_hmg_F",
  "O_G_Offroad_01_F",
  "O_G_Offroad_01_armed_F",	
  "rhsusf_m1025_w_s_m2",
  "rhsusf_m1025_d",
  "rhsusf_m1025_w",
  "rhs_tigr_vdv",
  "rhs_tigr_vmf",
  "rhs_tigr_msv",
  "rhs_tigr_vv",
  "rhs_tigr_3camo_vdv",
  "rhs_tigr_3camo_vmf",
  "rhs_tigr_3camo_msv",
  "rhs_tigr_3camo_vv",
  "rhs_tigr_ffv_vdv",
  "rhs_tigr_ffv_vmf",
  "rhs_tigr_ffv_msv",
  "rhs_tigr_ffv_vv",
  "rhs_tigr_ffv_3camo_vdv",
  "rhs_tigr_ffv_3camo_vv",
  "rhs_uaz_open_MSV_01",
  "rhsusf_m998_w_s_2dr",
  "rhsusf_m988_d_s_2dr",
  "rhsusf_m988_w_s_2dr_halftop",
  "rhsusf_m998_d_s_2dr_fulltop",
  "rhsusf_m998_w_s_2dr_fulltop"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["tank", 5],
	["car", 6],
	["motorcycle", 2],
	["truck_f", 100],
	["bus", 30],
	["kart_01_base_f", 2],
	["mrap_01_base_f", 12],
	["mrap_02_base_f", 12],
	["mrap_03_base_f", 12],
	["offroad_01_base_f", 10],
	["offroad_01_armed_base_f", 4],
	["quadbike_01_base_f", 3],
	["quadbike_base_f", 3],
	["b_truck_01_mover_f", 5],
	["b_truck_01_repair_f", 170],
	["b_truck_01_covered_f", 120],
	["b_truck_01_ammo_f", 120],
	["b_truck_01_box_f", 170],
	["truck_02_base_f", 120],
	["i_truck_02_medical_f", 100],
	["i_truck_02_fuel_f", 5],
	["i_truck_02_transport_f", 100],
	["o_truck_02_fuel_f", 5],
	["o_truck_02_transport_f", 100],
	["o_truck_03_ammo_f", 140],
	["o_truck_03_device_f", 5],
	["o_truck_03_fuel_f", 5],
	["van_01_base_f", 5],
	["c_van_01_box_f", 40],
	["c_van_01_transport_f", 25],
	["i_g_van_01_transport_f", 25],
	["wheeled_apc_f", 10]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	["kart_01_base_f", 40],
	["quadbike_01_base_f", 40],
	["ugv_01_base_f", 100]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
];